In [1]:
import pandas as pd
import numpy as np

input_file = "dataSet_v2.csv"
output_file = "dataSet_v2_fixed.csv"

In [2]:
#Reemplazar todas los semicolons por comas
with open(input_file, "r", encoding="utf-8") as infile, open(output_file, "w", encoding="utf-8") as outfile:
    for line in infile:
        fixed_line = line.replace(";", ",")
        outfile.write(fixed_line)

In [3]:
df = pd.read_csv(output_file, sep=",",  on_bad_lines="skip",  low_memory=False)

In [4]:
# Remover todas las columnas adicionales
df.drop(df.iloc[:, 14:287], inplace=True, axis=1)

In [5]:
cols_num = [
    'Serial Number',
    'List Year',
    'Assessed Value',
    'Sale Amount'
]

cols_float = [
    'Sales Ratio'
]

In [6]:
#Cambiar las columnas a tipo numero
for col in [*cols_num, *cols_float]:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    #Borrar todas las filas que tienen null en el id
    df = df.dropna(subset=[col])

In [7]:
#Cambiar las columnas con datos numericos a ser numero
for col in cols_num:
    df[col] = df[col].astype('int')
    
for col in cols_float:
    df[col] = df[col].astype('float')    

df['Date Recorded'] = pd.to_datetime(df['Date Recorded'])

In [8]:
df.head(10)

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Assessor Remarks,OPM remarks,Location
0,2020348,2020,2021-09-13,Ansonia,230 WAKELEE AVE,150500,325000,0.4630,Commercial,NaN,NaN,NaN,NaN,NaN
1,20002,2020,2020-10-02,Ashford,390 TURNPIKE RD,253000,430000,0.5883,Residential,Single Family,NaN,NaN,NaN,NaN
2,200212,2020,2021-03-09,Avon,5 CHESTNUT DRIVE,130400,179900,0.7248,Residential,Condo,NaN,NaN,NaN,NaN
3,200243,2020,2021-04-13,Avon,111 NORTHINGTON DRIVE,619290,890000,0.6958,Residential,Single Family,NaN,NaN,NaN,NaN
4,200377,2020,2021-07-02,Avon,70 FAR HILLS DRIVE,862330,1447500,0.5957,Residential,Single Family,NaN,NaN,NaN,NaN
5,200109,2020,2020-12-09,Avon,57 FAR HILLS DRIVE,847520,1250000,0.6780,Residential,Single Family,NaN,NaN,NaN,NaN
6,2020180,2020,2021-03-01,Berlin,1539 FARMINGTON AVE,234200,130000,1.8015,Residential,Two Family,08 - Part Interest,NaN,NaN,NaN
7,2020313,2020,2021-07-01,Berlin,216 WATCH HILL RD,412000,677500,0.6081,Residential,Single Family,NaN,NaN,NaN,NaN
8,200097,2020,2021-06-04,Bethany,23 AMITY RD,511000,795000,0.6427,Commercial,NaN,NaN,NaN,NaN,NaN
9,20139,2020,2020-12-16,Bethel,16 DEEPWOOD DRIVE,171360,335000,0.5115,Residential,Single Family,NaN,NaN,NaN,NaN

In [9]:
df['Sell Year'] = df['Date Recorded'].dt.year
df['Sell Year'] = df['Sell Year'].astype('Int64')

In [10]:
df.head(10)

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Assessor Remarks,OPM remarks,Location,Sell Year
0,2020348,2020,2021-09-13,Ansonia,230 WAKELEE AVE,150500,325000,0.4630,Commercial,NaN,NaN,NaN,NaN,NaN,2021
1,20002,2020,2020-10-02,Ashford,390 TURNPIKE RD,253000,430000,0.5883,Residential,Single Family,NaN,NaN,NaN,NaN,2020
2,200212,2020,2021-03-09,Avon,5 CHESTNUT DRIVE,130400,179900,0.7248,Residential,Condo,NaN,NaN,NaN,NaN,2021
3,200243,2020,2021-04-13,Avon,111 NORTHINGTON DRIVE,619290,890000,0.6958,Residential,Single Family,NaN,NaN,NaN,NaN,2021
4,200377,2020,2021-07-02,Avon,70 FAR HILLS DRIVE,862330,1447500,0.5957,Residential,Single Family,NaN,NaN,NaN,NaN,2021
5,200109,2020,2020-12-09,Avon,57 FAR HILLS DRIVE,847520,1250000,0.6780,Residential,Single Family,NaN,NaN,NaN,NaN,2020
6,2020180,2020,2021-03-01,Berlin,1539 FARMINGTON AVE,234200,130000,1.8015,Residential,Two Family,08 - Part Interest,NaN,NaN,NaN,2021
7,2020313,2020,2021-07-01,Berlin,216 WATCH HILL RD,412000,677500,0.6081,Residential,Single Family,NaN,NaN,NaN,NaN,2021
8,200097,2020,2021-06-04,Bethany,23 AMITY RD,511000,795000,0.6427,Commercial,NaN,NaN,NaN,NaN,NaN,2021
9,20139,2020,2020-12-16,Bethel,16 DEEPWOOD DRIVE,171360,335000,0.5115,Residential,Single Family,NaN,NaN,NaN,NaN,2020

In [13]:
#Ingreso anual
#¿Cuál es el ingreso anual de las propiedades vendidas?
result = df.groupby('Sell Year')['Sale Amount'].sum().reset_index()
print(result)

    Sell Year  Sale Amount
0        2001   3175872755
1        2002  15476278657
2        2003  13915000112
3        2004   4795804453
4        2005     36942348
5        2006     32200757
6        2007     59070121
7        2008     29133190
8        2009     23384861
9        2010     54236355
10       2011     23337070
11       2012     45079458
12       2013     30219359
13       2014     68305886
14       2015     67958636
15       2016     39698560
16       2017     38192196
17       2018     73913405
18       2019     94778034
19       2020   7392777094
20       2021  23283260504

In [15]:
#¿Qué tipo de propiedad tiene mayor facilidad de venta?
conteo_tipo_propiedades = df['Property Type'].value_counts().head(1)
print(conteo_tipo_propiedades)

Property Type
Residential    51271
Name: count, dtype: int64

In [17]:
#¿En cuál ciudad o pueblo se dan mayor cantidad de ventas de propiedades?
conteo_pueblo = df['Town'].value_counts().head(1)
print(conteo_pueblo)

Town
Stamford    7846
Name: count, dtype: int64

In [19]:
# ¿Qué elementos particulares tienen esas ciudades o pueblos?
filtered_df = df[df['Town'] == "Stamford"]
filtered_df.head(10)

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Assessor Remarks,OPM remarks,Location,Sell Year
200,11407,2001,2002-05-07,Stamford,27 NORTHILL ST,79730,210000,0.379667,NaN,NaN,NaN,NaN,NaN,NaN,2002
246,2000720,2020,2021-01-05,Stamford,57 HARBOR DRIVE GARAGE G-105B,19110,27500,0.694900,Residential,Condo,NaN,NaN,NaN,NaN,2021
247,2000737,2020,2021-01-06,Stamford,LOT 2 EDEN ROAD,208560,238000,0.876300,Vacant Land,NaN,NaN,NaN,NaN,NaN,2021
248,2000857,2020,2021-01-21,Stamford,0 SUMMER STREET #116-2A,109420,195000,0.561100,Residential,Condo,NaN,NaN,NaN,NaN,2021
249,2001101,2020,2021-03-04,Stamford,385 ERSKINE ROAD,599810,950000,0.631300,Residential,Single Family,NaN,NaN,NaN,NaN,2021
250,2001250,2020,2021-03-25,Stamford,28 VERNON PLACE,403190,810000,0.497700,Residential,Three Family,NaN,NaN,NaN,NaN,2021
251,2001286,2020,2021-03-30,Stamford,1156 STILLWATER ROAD,438860,652000,0.673000,Residential,Single Family,NaN,NaN,NaN,NaN,2021
252,2001493,2020,2021-05-03,Stamford,18 BUNGALOW PARK,238890,400000,0.597200,Residential,Single Family,NaN,NaN,NaN,NaN,2021
253,2001570,2020,2021-05-14,Stamford,52 ORCHARD STREET,486230,930000,0.522800,Commercial,NaN,NaN,NaN,NaN,NaN,2021
254,2001590,2020,2021-05-17,Stamford,37 CROSS ROAD,423700,533350,0.794400,Residential,Two Family,NaN,NaN,NaN,NaN,2021

In [33]:
max_val = filtered_df['Sale Amount'].max()
print(max_val)

154000000

In [34]:
min_val = filtered_df['Sale Amount'].min()
print(min_val)

10

In [29]:
foo_df = filtered_df[filtered_df['Sale Amount'] == 10]

foo_df.head(1)

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Assessor Remarks,OPM remarks,Location,Sell Year
92334,10717,2001,2002-01-24,Stamford,95 PROSPECT ST,221060,10,22106.0,NaN,NaN,8,NaN,NaN,NaN,2002

In [37]:
comercial_df = df[df["Property Type"] == "Commercial"]
residencial_df = df[df["Property Type"] == "Residential"]

In [39]:
#¿Cuál es el costo promedio de las propiedades residenciales y comerciales?
print("El promedio comercial", comercial_df["Sale Amount"].mean())
print("El promedio residencial", residencial_df["Sale Amount"].mean())

El promedio comercial 1907316.328079393
El promedio residencial 490270.6977043553

In [41]:
#. ¿Cuál es tipo de propiedades residenciales que se vende con mayor frecuencia, donde y con que costo promedio?
conteo_tipo_residenciales = df['Residential Type'].value_counts().head(1)
print(conteo_tipo_residenciales)

Residential Type
Single Family    36379
Name: count, dtype: int64

In [42]:
filtrado_tipo_residencial_df = df[df['Residential Type'] == "Single Family"]

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Assessor Remarks,OPM remarks,Location,Sell Year
1,20002,2020,2020-10-02,Ashford,390 TURNPIKE RD,253000,430000,0.5883,Residential,Single Family,NaN,NaN,NaN,NaN,2020

In [44]:
#donde
print(filtrado_tipo_residencial_df['Town'].value_counts().head(1))

Town
Stamford    1210
Name: count, dtype: int64