<h1>Proyecto Analisis de Datos</h1>

<a href="https://www.kaggle.com/datasets/utkarshx27/real-estate-sales-2001-2020-gl">Metadata de los datos</a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
cols = [
    "serial_number",
    "list_year",
    "date_recorded",
    "town",
    "address",
    "assessed_value",
    "sale_amount",
    "sales_ratio",
    "property_type",
    "residential_type",
    "non_use_code",
    "assessor_remarks",
    "opm_remarks",
    "location"
]

<h3>Carga de datos</h3>

In [3]:
dfBienesRaices = pd.read_csv("Real_Estate_Sales_2001-2020_GL.csv", names=cols, low_memory=False)
dfBienesRaices.reset_index(drop=True, inplace=True)

In [4]:
#Borrar la fila de headers
dfBienesRaices.drop(0, inplace=True)

In [5]:
#Sacar los nulos
def sacar_nulos():
    dfTemp = dfBienesRaices.isnull()
    
    for variable in dfTemp.columns.values.tolist():
        print(dfTemp[variable].value_counts())
        print('')

In [6]:
sacar_nulos()

serial_number
False    997213
Name: count, dtype: int64

list_year
False    997213
Name: count, dtype: int64

date_recorded
False    997211
True          2
Name: count, dtype: int64

town
False    997213
Name: count, dtype: int64

address
False    997162
True         51
Name: count, dtype: int64

assessed_value
False    997213
Name: count, dtype: int64

sale_amount
False    997213
Name: count, dtype: int64

sales_ratio
False    997213
Name: count, dtype: int64

property_type
False    614767
True     382446
Name: count, dtype: int64

residential_type
False    608904
True     388309
Name: count, dtype: int64

non_use_code
True     707532
False    289681
Name: count, dtype: int64

assessor_remarks
True     847349
False    149864
Name: count, dtype: int64

opm_remarks
True     987279
False      9934
Name: count, dtype: int64

location
True     799516
False    197697
Name: count, dtype: int64

In [7]:
dfTemp = dfBienesRaices.isnull()
dfTemp.head(10)

,serial_number,list_year,date_recorded,town,address,assessed_value,sale_amount,sales_ratio,property_type,residential_type,non_use_code,assessor_remarks,opm_remarks,location
1,False,False,False,False,False,False,False,False,False,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,True,True,True,True
5,False,False,False,False,False,False,False,False,False,False,True,True,True,True
6,False,False,False,False,False,False,False,False,False,False,True,True,True,True
7,False,False,False,False,False,False,False,False,False,False,False,True,True,True
8,False,False,False,False,False,False,False,False,False,False,True,True,True,True
9,False,False,False,False,False,False,False,False,False,True,True,True,True,True
10,False,False,False,False,False,False,False,False,False,False,True,True,True,True

In [8]:
#Borrar todas las filas que tienen nulos en todas las columnas
dfBienesRaices.dropna(how="all", inplace=True)

In [9]:
sacar_nulos()

serial_number
False    997213
Name: count, dtype: int64

list_year
False    997213
Name: count, dtype: int64

date_recorded
False    997211
True          2
Name: count, dtype: int64

town
False    997213
Name: count, dtype: int64

address
False    997162
True         51
Name: count, dtype: int64

assessed_value
False    997213
Name: count, dtype: int64

sale_amount
False    997213
Name: count, dtype: int64

sales_ratio
False    997213
Name: count, dtype: int64

property_type
False    614767
True     382446
Name: count, dtype: int64

residential_type
False    608904
True     388309
Name: count, dtype: int64

non_use_code
True     707532
False    289681
Name: count, dtype: int64

assessor_remarks
True     847349
False    149864
Name: count, dtype: int64

opm_remarks
True     987279
False      9934
Name: count, dtype: int64

location
True     799516
False    197697
Name: count, dtype: int64

In [10]:
dfBienesRaices.head(20)

,serial_number,list_year,date_recorded,town,address,assessed_value,sale_amount,sales_ratio,property_type,residential_type,non_use_code,assessor_remarks,opm_remarks,location
1,2020348,2020,09/13/2021,Ansonia,230 WAKELEE AVE,150500.00,325000.00,0.463,Commercial,NaN,NaN,NaN,NaN,NaN
2,20002,2020,10/02/2020,Ashford,390 TURNPIKE RD,253000.00,430000.00,0.5883,Residential,Single Family,NaN,NaN,NaN,NaN
3,200212,2020,03/09/2021,Avon,5 CHESTNUT DRIVE,130400.00,179900.00,0.7248,Residential,Condo,NaN,NaN,NaN,NaN
4,200243,2020,04/13/2021,Avon,111 NORTHINGTON DRIVE,619290.00,890000.00,0.6958,Residential,Single Family,NaN,NaN,NaN,NaN
5,200377,2020,07/02/2021,Avon,70 FAR HILLS DRIVE,862330.00,1447500.00,0.5957,Residential,Single Family,NaN,NaN,NaN,NaN
6,200109,2020,12/09/2020,Avon,57 FAR HILLS DRIVE,847520.00,1250000.00,0.678,Residential,Single Family,NaN,NaN,NaN,NaN
7,2020180,2020,03/01/2021,Berlin,1539 FARMINGTON AVE,234200.00,130000.00,1.8015,Residential,Two Family,08 - Part Interest,NaN,NaN,NaN
8,2020313,2020,07/01/2021,Berlin,216 WATCH HILL RD,412000.00,677500.00,0.6081,Residential,Single Family,NaN,NaN,NaN,NaN
9,200097,2020,06/04/2021,Bethany,23 AMITY RD,511000.00,795000.00,0.6427,Commercial,NaN,NaN,NaN,NaN,NaN
10,20139,2020,12/16/2020,Bethel,16 DEEPWOOD DRIVE,171360.00,335000.00,0.5115,Residential,Single Family,NaN,NaN,NaN,NaN
11,200086,2020,08/10/2021,Bethlehem,39 WOODLAND RD,168900.00,352000.00,0.4798,Residential,Single Family,NaN,NaN,NaN,POINT (-73.18197 41.64672)
12,2000381,2020,09/13/2021,Bloomfield,9 SADDLE RIDGE,163730.00,250000.00,0.6549,Residential,Condo,NaN,NaN,NaN,NaN
13,200258,2020,01/22/2021,Branford,34 SUNRISE COVE CAMP,530500.00,700000.00,0.7578,Residential,Single Family,NaN,WATERFRONT/COTTAGE ONLY/LAND IS ASSOCIATION OWNED,NaN,NaN
14,200804,2020,09/28/2021,Branford,119 MONTOWESE ST,455100.00,650000.00,0.7001,Commercial,NaN,NaN,NaN,NaN,NaN
15,201295,2020,09/09/2021,Bristol,609 CAMP ST,144340.00,249900.00,0.5775,Residential,Single Family,NaN,NaN,NaN,NaN
16,200032,2020,10/08/2020,Bristol,9 LESLIE COURT,94920.00,155000.00,0.6123,Residential,Single Family,NaN,NaN,NaN,NaN
17,200354,2020,12/29/2020,Bristol,391 TIFFANY LA,173740.00,299000.00,0.581,Residential,Single Family,NaN,NaN,NaN,NaN
18,200527,2020,03/01/2021,Bristol,25 WARD ST,85680.00,183000.00,0.4681,Residential,Two Family,NaN,NaN,NaN,NaN
19,201212,2020,08/23/2021,Bristol,8 JENNINGS TERR,88060.00,91000.00,0.9676,Residential,Single Family,14 - Foreclosure,FORECLOSURE SALE OUT OF BANK,NaN,NaN
20,20000050,2020,11/05/2020,Brookfield,4 CHELSEA CT,105110.00,160000.00,0.6569375,Residential,Condo,NaN,NaN,NaN,NaN

In [11]:
dfBienesRaices["list_year"].unique()

array(['2020', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019'], dtype=object)

In [30]:
#Cambiar sales amount a float
dfBienesRaices[["sale_amount"]] = dfBienesRaices[["sale_amount"]].astype(int)

dfBienesRaices.head(20)

,serial_number,list_year,date_recorded,town,address,assessed_value,sale_amount,sales_ratio,property_type,residential_type,non_use_code,assessor_remarks,opm_remarks,location
1,2020348,2020,09/13/2021,Ansonia,230 WAKELEE AVE,150500.00,325000,0.463,Commercial,NaN,NaN,NaN,NaN,NaN
2,20002,2020,10/02/2020,Ashford,390 TURNPIKE RD,253000.00,430000,0.5883,Residential,Single Family,NaN,NaN,NaN,NaN
3,200212,2020,03/09/2021,Avon,5 CHESTNUT DRIVE,130400.00,179900,0.7248,Residential,Condo,NaN,NaN,NaN,NaN
4,200243,2020,04/13/2021,Avon,111 NORTHINGTON DRIVE,619290.00,890000,0.6958,Residential,Single Family,NaN,NaN,NaN,NaN
5,200377,2020,07/02/2021,Avon,70 FAR HILLS DRIVE,862330.00,1447500,0.5957,Residential,Single Family,NaN,NaN,NaN,NaN
6,200109,2020,12/09/2020,Avon,57 FAR HILLS DRIVE,847520.00,1250000,0.678,Residential,Single Family,NaN,NaN,NaN,NaN
7,2020180,2020,03/01/2021,Berlin,1539 FARMINGTON AVE,234200.00,130000,1.8015,Residential,Two Family,08 - Part Interest,NaN,NaN,NaN
8,2020313,2020,07/01/2021,Berlin,216 WATCH HILL RD,412000.00,677500,0.6081,Residential,Single Family,NaN,NaN,NaN,NaN
9,200097,2020,06/04/2021,Bethany,23 AMITY RD,511000.00,795000,0.6427,Commercial,NaN,NaN,NaN,NaN,NaN
10,20139,2020,12/16/2020,Bethel,16 DEEPWOOD DRIVE,171360.00,335000,0.5115,Residential,Single Family,NaN,NaN,NaN,NaN
11,200086,2020,08/10/2021,Bethlehem,39 WOODLAND RD,168900.00,352000,0.4798,Residential,Single Family,NaN,NaN,NaN,POINT (-73.18197 41.64672)
12,2000381,2020,09/13/2021,Bloomfield,9 SADDLE RIDGE,163730.00,250000,0.6549,Residential,Condo,NaN,NaN,NaN,NaN
13,200258,2020,01/22/2021,Branford,34 SUNRISE COVE CAMP,530500.00,700000,0.7578,Residential,Single Family,NaN,WATERFRONT/COTTAGE ONLY/LAND IS ASSOCIATION OWNED,NaN,NaN
14,200804,2020,09/28/2021,Branford,119 MONTOWESE ST,455100.00,650000,0.7001,Commercial,NaN,NaN,NaN,NaN,NaN
15,201295,2020,09/09/2021,Bristol,609 CAMP ST,144340.00,249900,0.5775,Residential,Single Family,NaN,NaN,NaN,NaN
16,200032,2020,10/08/2020,Bristol,9 LESLIE COURT,94920.00,155000,0.6123,Residential,Single Family,NaN,NaN,NaN,NaN
17,200354,2020,12/29/2020,Bristol,391 TIFFANY LA,173740.00,299000,0.581,Residential,Single Family,NaN,NaN,NaN,NaN
18,200527,2020,03/01/2021,Bristol,25 WARD ST,85680.00,183000,0.4681,Residential,Two Family,NaN,NaN,NaN,NaN
19,201212,2020,08/23/2021,Bristol,8 JENNINGS TERR,88060.00,91000,0.9676,Residential,Single Family,14 - Foreclosure,FORECLOSURE SALE OUT OF BANK,NaN,NaN
20,20000050,2020,11/05/2020,Brookfield,4 CHELSEA CT,105110.00,160000,0.6569375,Residential,Condo,NaN,NaN,NaN,NaN

In [31]:
# #¿Cuál es el ingreso anual de las propiedades vendidas?
df_ventas = dfBienesRaices.groupby('list_year')['sale_amount'].sum().reset_index()

In [32]:
print(df_ventas)

   list_year  sale_amount
0       2001  14671668335
1       2002  17687185857
2       2003  21020152793
3       2004  31966245823
4       2005  22424983827
5       2006  23191375510
6       2007  15518803446
7       2008  10666103724
8       2009  15100980907
9       2010  11107540414
10      2011  12167673424
11      2012  14226518438
12      2013  16517079160
13      2014  19895675672
14      2015  16135823472
15      2016  25272800660
16      2017  17968045803
17      2018  19458446134
18      2019  24778187621
19      2020  40285754082